import Footer from "@/components/footer/footer";
import Navbar from "@/components/navbar";
import type { Metadata } from "next";
import { Charm, Montserrat } from "next/font/google";
import "./globals.css";

const charm = Charm({
  subsets: ["latin"],
  weight: "400",
  variable: "--charm",
});

const montserrat = Montserrat({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${charm.variable}`}>
      <body
        className={`${montserrat.className} bg-black p-5 text-white antialiased`}
        suppressHydrationWarning
      >
        <Navbar />
        <div className="flex flex-col gap-y-6">
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
